export const MEAT_TYPE = ["Bovina", "Suína", "Aves", "Peixes"] as const;

export const STATES = [
  "Acre",
  "Alagoas",
  "Amapá",
  "Amazonas",
  "Bahia",
  "Ceará",
  "Distrito Federal",
  "Espírito Santo",
  "Goiás",
  "Maranhão",
  "Mato Grosso",
  "Mato Grosso do Sul",
  "Minas Gerais",
  "Pará",
  "Paraíba",
  "Paraná",
  "Pernambuco",
  "Piauí",
  "Rio de Janeiro",
  "Rio Grande do Norte",
  "Rio Grande do Sul",
  "Rondônia",
  "Roraima",
  "Santa Catarina",
  "São Paulo",
  "Sergipe",
  "Tocantins",
];

export const CITIES = [
  "Arapiraca",
  "Atalaia",
  "Coruripe",
  "Delmiro Gouveia",
  "Maceió",
  "Maragogi",
  "Marechal Deodoro",
  "Palmeira dos Índios",
  "Penedo",
  "Rio Largo",
  "São Miguel dos Campos",
  "União dos Palmares",
  "Amapá",
  "Calçoene",
  "Cutias",
  "Ferreira Gomes",
  "Laranjal do Jari",
  "Macapá",
  "Mazagão",
  "Oiapoque",
  "Porto Grande",
  "Santana",
  "Serra do Navio",
  "Vitória do Jari",
  "Autazes",
  "Benjamin Constant",
  "Coari",
  "Eirunepé",
  "Humaitá",
  "Itacoatiara",
  "Lábrea",
  "Manaus",
  "Manacapuru",
  "Maués",
  "Parintins",
  "Tabatinga",
  "Tefé",
];
